name: refresh-site
on:
  schedule:
    - cron:  '0 5 * * *'        # every day 05:00 UTC ≈ 07:00 CET
  workflow_dispatch:            # run manually from the Actions tab
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4             # :contentReference[oaicite:0]{index=0}
      - uses: actions/setup-python@v5         # :contentReference[oaicite:1]{index=1}
        with: { python-version: '3.11' }
      - name: Install Python deps
        run: pip install -r requirements.txt
      - name: Run scraper
        env: { OMDB_KEY: ${{ secrets.OMDB_KEY }} }
        run: python scrape.py
      - name: Commit & push if changed
        run: |
          git config --global user.name  github-actions
          git config --global user.email actions@github.com
          git add index.html
          git commit -m "auto: refresh $(date -u '+%Y-%m-%d')" || exit 0
          git push

